# This is the demo Dockerfile for the generated template project, please change accordingly before building image from it.
# Run the following command to build image: docker build -f ./Dockerfile --build-arg APP_FILE=quickstart-service--0.0.1-SNAPSHOT.jar -t demo:latest .
FROM openjdk:17-jdk-alpine AS builder

# 设置工作目录
WORKDIR /build
COPY . /build

RUN chmod +x ./mvnw
RUN ./mvnw clean package -U -DskipTests

# JAR file will be specified by passing in a build time argument to docker build
ARG APP_DIR
ARG APP_FILE
ARG APP_PORT

# 暴露 API 端口（根据实际需要修改端口号）
EXPOSE ${APP_PORT}

# 将 API JAR 文件复制到镜像中
RUN cp ./${APP_DIR}/target/${APP_FILE} auth.jar

FROM openjdk:17-jdk-alpine

COPY --from=builder /build/auth.jar auth.jar

# 设置启动命令
CMD ["java","-jar","app.jar"]